<#
.SYNOPSIS
    Starts the workflow engine locally, generating and reusing the keys it needs.

.DESCRIPTION
    The engine refuses to start without a JWT signing key and an encryption key, which is correct but
    tedious to satisfy by hand on every run. This script generates them once into .env.local and reuses
    them afterwards, so tokens and encrypted secrets survive a restart.

    .env.local is gitignored and contains real keys. It is a local development convenience: in any shared
    environment these values belong in a secret manager, injected as environment variables, and never on
    disk beside the code.

    Keys are generated with the .NET cryptographic RNG rather than Get-Random, which is not suitable for
    key material, and without requiring openssl, which a stock Windows install does not have.

.PARAMETER Port
    Port to listen on. Defaults to 8080.

.PARAMETER BootstrapAdmin
    Create a first administrator on this run. Prompts for the password rather than taking it as a
    parameter, so it does not land in the PowerShell history file.

.PARAMETER Rotate
    Discard the stored keys and generate new ones. Invalidates every existing token and makes previously
    encrypted secrets unreadable.

.EXAMPLE
    ./run-local.ps1
    Starts on 8080, reusing or creating .env.local.

.EXAMPLE
    ./run-local.ps1 -BootstrapAdmin
    Starts and creates the first ADMIN account, prompting for its password.
#>
[CmdletBinding()]
param(
    [int]$Port = 8080,
    [switch]$BootstrapAdmin,
    [switch]$Rotate
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$envFile = Join-Path $root '.env.local'
$jar = Join-Path $root 'workflow-engine-core\target\workflow-engine.jar'

# ---------------------------------------------------------------- key material

function New-Secret {
    param([int]$Bytes)
    # The cryptographic RNG. Get-Random is a pseudo-random generator and must never produce a key.
    $buffer = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buffer)
    return [Convert]::ToBase64String($buffer)
}

function Read-EnvFile {
    param([string]$Path)
    $values = @{}
    if (Test-Path $Path) {
        foreach ($line in Get-Content $Path) {
            $trimmed = $line.Trim()
            if ($trimmed.Length -eq 0 -or $trimmed.StartsWith('#')) { continue }
            $split = $trimmed.IndexOf('=')
            if ($split -gt 0) {
                $values[$trimmed.Substring(0, $split)] = $trimmed.Substring($split + 1)
            }
        }
    }
    return $values
}

if ($Rotate -and (Test-Path $envFile)) {
    Write-Warning 'Rotating keys. Every existing token becomes invalid and secrets encrypted with the old key cannot be read.'
    Remove-Item -LiteralPath $envFile
}

$config = Read-EnvFile $envFile
$created = $false

# 48 bytes for HS256 signing; 32 bytes exactly for AES-256, which the engine enforces.
if (-not $config.ContainsKey('JWT_SECRET')) { $config['JWT_SECRET'] = New-Secret 48; $created = $true }
if (-not $config.ContainsKey('APP_ENCRYPTION_KEY')) { $config['APP_ENCRYPTION_KEY'] = New-Secret 32; $created = $true }
if (-not $config.ContainsKey('WORKFLOW_SECRETS_KEY')) { $config['WORKFLOW_SECRETS_KEY'] = New-Secret 32; $created = $true }

if ($created) {
    $header = @(
        '# Generated by run-local.ps1. Local development only.',
        '#',
        '# These are real keys. This file is gitignored; keep it that way. In any shared environment,',
        '# supply these as environment variables from a secret manager instead of from a file on disk.',
        '#',
        '# Rotating JWT_SECRET signs everyone out. Rotating APP_ENCRYPTION_KEY or WORKFLOW_SECRETS_KEY',
        '# makes every stored secret unreadable, because the values are encrypted, not hashed.',
        ''
    )
    $body = $config.Keys | Sort-Object | ForEach-Object { "$_=$($config[$_])" }
    Set-Content -LiteralPath $envFile -Value ($header + $body) -Encoding ASCII
    Write-Host "Generated keys into .env.local" -ForegroundColor Green
}
else {
    Write-Host "Reusing keys from .env.local" -ForegroundColor DarkGray
}

# --------------------------------------------------------------- sanity checks

if (-not (Test-Path $jar)) {
    Write-Error "Not built yet. Run: mvn -pl workflow-engine-core -am install`n(looked for $jar)"
    exit 1
}

$mongo = Get-NetTCPConnection -LocalPort 27017 -State Listen -ErrorAction SilentlyContinue
if (-not $mongo) {
    Write-Warning 'Nothing is listening on 27017. The engine will start but every request touching the database will fail.'
}

$inUse = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
if ($inUse) {
    # A locked jar during a rebuild is the usual symptom of forgetting an engine is already running.
    Write-Error "Port $Port is already in use by pid $($inUse.OwningProcess | Select-Object -First 1). Stop it, or pass -Port."
    exit 1
}

# ------------------------------------------------------------------ environment

foreach ($key in $config.Keys) {
    Set-Item -Path "env:$key" -Value $config[$key]
}
$env:SERVER_PORT = "$Port"
$env:MONGODB_URI = if ($config.ContainsKey('MONGODB_URI')) { $config['MONGODB_URI'] } else { 'mongodb://localhost:27017/workflow_engine' }
$env:MONGODB_DATABASE = if ($config.ContainsKey('MONGODB_DATABASE')) { $config['MONGODB_DATABASE'] } else { 'workflow_engine' }

if ($BootstrapAdmin) {
    $username = Read-Host 'Administrator username'
    $email = Read-Host 'Administrator email'
    # Read as a SecureString so it is not echoed and does not enter the PowerShell history.
    $secure = Read-Host 'Administrator password' -AsSecureString
    $plain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure))

    $env:BOOTSTRAP_ADMIN_ENABLED = 'true'
    $env:BOOTSTRAP_ADMIN_USERNAME = $username
    $env:BOOTSTRAP_ADMIN_EMAIL = $email
    $env:BOOTSTRAP_ADMIN_PASSWORD = $plain

    Write-Host 'An administrator will be created if none exists. Change the password after signing in.' -ForegroundColor Yellow
}
else {
    $env:BOOTSTRAP_ADMIN_ENABLED = 'false'
}

# ------------------------------------------------------------------------- run

$java = if ($env:JAVA_HOME) { Join-Path $env:JAVA_HOME 'bin\java.exe' } else { 'java' }

Write-Host ''
Write-Host "Starting the workflow engine on http://localhost:$Port" -ForegroundColor Cyan
Write-Host "  database  $($env:MONGODB_DATABASE)" -ForegroundColor DarkGray
Write-Host "  API docs  http://localhost:$Port/swagger-ui.html" -ForegroundColor DarkGray
Write-Host ''

try {
    & $java -jar $jar
}
finally {
    # Clear the bootstrap password from this session even if the engine exits abnormally.
    Remove-Item Env:BOOTSTRAP_ADMIN_PASSWORD -ErrorAction SilentlyContinue
}
