package com.orchpilot.workflow.plugins.azure;
import com.orchpilot.workflow.sdk.context.*;
import com.orchpilot.workflow.sdk.node.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
class AzurePluginTest{
 @Test void publishesAllNodesInOneCategory(){AzurePlugin p=new AzurePlugin();assertThat(p.getNodeDefinitions()).hasSize(16).allSatisfy(n->assertThat(n.category()).isEqualTo("Azure"));assertThat(p.getNodeDefinitions()).filteredOn(NodeDefinition::destructive).extracting(NodeDefinition::nodeType).containsExactlyInAnyOrder("AZURE_VM_DELETE","AZURE_VNET_DELETE","AZURE_AKS_DELETE");}
 @Test void authenticatesAndCallsArmForSafeList(){PluginContext pc=mock(PluginContext.class);when(pc.logger()).thenReturn(mock(PluginLogger.class));PluginHttpClient http=mock(PluginHttpClient.class);SecretProvider secrets=mock(SecretProvider.class);when(pc.http()).thenReturn(http);when(pc.secrets()).thenReturn(secrets);when(secrets.require("azure.test")).thenReturn("{\"tenantId\":\"tenant\",\"clientId\":\"client\",\"clientSecret\":\"secret\"}");when(http.execute(any())).thenAnswer(invocation->{HttpRequestSpec r=invocation.getArgument(0);return r.uri().contains("login.microsoftonline.com")?new HttpResponseView(200,Map.of("Content-Type",List.of("application/json")),"{\"access_token\":\"token\"}",1):new HttpResponseView(200,Map.of("Content-Type",List.of("application/json")),"{\"value\":[]}",1);});AzurePlugin p=new AzurePlugin();p.initialize(pc);NodeExecutionContext e=mock(NodeExecutionContext.class);when(e.nodeType()).thenReturn("AZURE_VM_LIST");when(e.timeoutMillis()).thenReturn(5000L);when(e.configuration()).thenReturn(new MapConfiguration(Map.of("credentialsSecret","azure.test","subscriptionId","sub","resourceGroup","rg")));NodeExecutionResult result=p.execute(e);assertThat(result.isSuccess()).isTrue();verify(http).execute(argThat(r->r.uri().equals("https://management.azure.com/subscriptions/sub/resourceGroups/rg/providers/Microsoft.Compute/virtualMachines?api-version=2024-07-01")&&"Bearer token".equals(r.headers().get("Authorization"))));}
 @Test void deleteRequiresConfirmationBeforeCredentialAccess(){PluginContext pc=mock(PluginContext.class);when(pc.logger()).thenReturn(mock(PluginLogger.class));AzurePlugin p=new AzurePlugin();p.initialize(pc);NodeExecutionContext e=mock(NodeExecutionContext.class);when(e.nodeType()).thenReturn("AZURE_AKS_DELETE");when(e.configuration()).thenReturn(new MapConfiguration(Map.of("credentialsSecret","azure.test","subscriptionId","sub","resourceGroup","rg","clusterName","c")));NodeExecutionResult result=p.execute(e);assertThat(result.errorCode()).isEqualTo("AZURE_CONFIRMATION_REQUIRED");verify(pc,never()).secrets();}
}
