package com.orchpilot.workflow.support;

import com.orchpilot.workflow.sdk.plugin.PluginApi;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.jar.Attributes;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import java.util.jar.Manifest;

/**
 * Builds real plugin JARs at test time.
 *
 * <p>Packaging an actual compiled class rather than mocking the loader is what makes the plugin tests worth having: they
 * exercise manifest discovery, child-first delegation, instantiation and initialisation exactly as a production upload
 * would. The class bytes are read from the test classpath, so the plugin under test is ordinary Java that the compiler
 * has already checked.
 *
 * <p>Note that the packaged class is also visible on the parent classpath. That is deliberate: because the plugin class
 * loader is child-first, tests can assert that the class actually came from the JAR rather than from the parent, which
 * is the property the whole isolation model rests on.
 */
public final class TestJars {

    private TestJars() {
    }

    /**
     * @param mainClass         plugin implementation to declare in the manifest
     * @param additionalClasses other classes to include, such as helpers the plugin needs
     * @return the bytes of a plugin JAR
     */
    public static byte[] pluginJar(Class<?> mainClass, Class<?>... additionalClasses) {
        Manifest manifest = new Manifest();
        Attributes attributes = manifest.getMainAttributes();
        attributes.put(Attributes.Name.MANIFEST_VERSION, "1.0");
        attributes.putValue(PluginApi.MANIFEST_PLUGIN_CLASS, mainClass.getName());
        attributes.putValue(PluginApi.MANIFEST_API_VERSION, String.valueOf(PluginApi.VERSION));
        return build(manifest, classEntries(mainClass, additionalClasses), Map.of());
    }

    /**
     * Builds a JAR that declares its plugin through {@link java.util.ServiceLoader} instead of the manifest, so the
     * second discovery mechanism is covered too.
     *
     * @param mainClass plugin implementation
     * @return the bytes of a plugin JAR
     */
    public static byte[] serviceLoaderPluginJar(Class<?> mainClass) {
        Manifest manifest = new Manifest();
        manifest.getMainAttributes().put(Attributes.Name.MANIFEST_VERSION, "1.0");
        Map<String, String> resources = Map.of(
                "META-INF/services/com.orchpilot.workflow.sdk.plugin.WorkflowPlugin",
                "# generated by TestJars\n" + mainClass.getName() + "\n");
        return build(manifest, classEntries(mainClass), resources);
    }

    /**
     * @param manifest  manifest to write, or {@code null} for none
     * @param classes   entry name to class bytes
     * @param resources entry name to text content
     * @return the bytes of a JAR
     */
    public static byte[] build(Manifest manifest, Map<String, byte[]> classes, Map<String, String> resources) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (JarOutputStream jar = manifest == null
                ? new JarOutputStream(out)
                : new JarOutputStream(out, manifest)) {
            for (Map.Entry<String, byte[]> entry : classes.entrySet()) {
                jar.putNextEntry(new JarEntry(entry.getKey()));
                jar.write(entry.getValue());
                jar.closeEntry();
            }
            for (Map.Entry<String, String> entry : resources.entrySet()) {
                jar.putNextEntry(new JarEntry(entry.getKey()));
                jar.write(entry.getValue().getBytes(StandardCharsets.UTF_8));
                jar.closeEntry();
            }
        } catch (IOException ex) {
            throw new UncheckedIOException("Could not build the test JAR", ex);
        }
        return out.toByteArray();
    }

    /**
     * @param name    entry name
     * @param content text content
     * @return a JAR containing a single text resource and no manifest
     */
    public static byte[] resourceOnlyJar(String name, String content) {
        return build(null, Map.of(), Map.of(name, content));
    }

    private static Map<String, byte[]> classEntries(Class<?> mainClass, Class<?>... additional) {
        Map<String, byte[]> entries = new LinkedHashMap<>();
        entries.put(entryName(mainClass), readClassBytes(mainClass));
        for (Class<?> extra : additional) {
            entries.put(entryName(extra), readClassBytes(extra));
        }
        return entries;
    }

    private static String entryName(Class<?> type) {
        return type.getName().replace('.', '/') + ".class";
    }

    private static byte[] readClassBytes(Class<?> type) {
        String resource = entryName(type);
        try (InputStream in = type.getClassLoader().getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("Could not find compiled bytes for " + type.getName());
            }
            return in.readAllBytes();
        } catch (IOException ex) {
            throw new UncheckedIOException("Could not read " + resource, ex);
        }
    }
}
