package com.orchpilot.workflow.plugins.azure;
import com.orchpilot.workflow.sdk.context.*;
import com.orchpilot.workflow.sdk.exception.PluginConfigurationException;
import com.orchpilot.workflow.sdk.json.Json;
import com.orchpilot.workflow.sdk.node.*;
import com.orchpilot.workflow.sdk.plugin.*;
import com.orchpilot.workflow.sdk.schema.SchemaBuilder;
import java.util.*;

/** Azure Resource Manager integration. All contributed nodes intentionally share one Azure category. */
public final class AzurePlugin implements WorkflowNodePlugin{
 private volatile PluginContext context;private final AzureAuth auth=new AzureAuth();
 public String getId(){return "azure";}public String getName(){return "Azure";}public String getVersion(){return "1.0.0";}public String getDescription(){return "Manage Azure Virtual Machines, networking and AKS.";}public PluginType getPluginType(){return PluginType.NODE;}
 public void initialize(PluginContext c){context=c;c.logger().info("Azure plugin initialised");}public void destroy(){if(context!=null)context.logger().info("Azure plugin destroyed");}
 public List<NodeDefinition> getNodeDefinitions(){List<NodeDefinition> out=new ArrayList<>();for(AzureOperation op:AzureOperation.values())out.add(NodeDefinition.builder(op.nodeType).displayName(op.displayName).description(description(op)).category("Azure").icon("cloud").configurationSchema(schema(op)).outputVariables("success","operation","subscriptionId","resourceGroup","statusCode","response","asyncOperationUrl").idempotent(op.readOnly).supportsRetry(true).supportsAI(true).destructive(op.destructive).build());return List.copyOf(out);}
 private static String description(AzureOperation op){return switch(op){case VM_LIST->"List virtual machines in a resource group.";case VM_GET->"Read a virtual machine and instance view.";case VM_CREATE->"Create or update a Linux virtual machine.";case VM_START->"Start a virtual machine.";case VM_DEALLOCATE->"Stop and deallocate a virtual machine.";case VM_RESTART->"Restart a virtual machine.";case VM_DELETE->"Permanently delete a virtual machine.";case VNET_LIST->"List virtual networks.";case VNET_CREATE->"Create or update a virtual network.";case VNET_DELETE->"Delete a virtual network.";case SUBNET_CREATE->"Create or update a subnet.";case NSG_CREATE->"Create or update a network security group.";case AKS_LIST->"List AKS managed clusters.";case AKS_GET->"Read an AKS managed cluster.";case AKS_CREATE->"Create or update an AKS managed cluster with managed identity.";case AKS_DELETE->"Delete an AKS managed cluster.";};}
 private static Map<String,Object> schema(AzureOperation op){SchemaBuilder s=SchemaBuilder.object().secretRef("credentialsSecret","Azure service-principal secret name",true).withDescription("credentialsSecret","Name of an azure.* secret containing tenantId, clientId and clientSecret.").string("subscriptionId","Subscription ID",true).string("resourceGroup","Resource group",true);
  switch(op){case VM_LIST,VNET_LIST,AKS_LIST->{}case VM_GET,VM_START,VM_DEALLOCATE,VM_RESTART,VM_DELETE->s.string("vmName","Virtual machine name",true);case VM_CREATE->s.string("vmName","Virtual machine name",true).string("location","Azure region",true).string("vmSize","VM size",false).withDefault("vmSize","Standard_B2s").string("networkInterfaceId","Network interface resource ID",true).string("adminUsername","Administrator username",true).text("sshPublicKey","SSH public key",true).string("imagePublisher","Image publisher",false).withDefault("imagePublisher","Canonical").string("imageOffer","Image offer",false).withDefault("imageOffer","0001-com-ubuntu-server-jammy").string("imageSku","Image SKU",false).withDefault("imageSku","22_04-lts-gen2").string("imageVersion","Image version",false).withDefault("imageVersion","latest");case VNET_CREATE->s.string("vnetName","Virtual network name",true).string("location","Azure region",true).string("addressPrefix","Address prefix",true);case VNET_DELETE->s.string("vnetName","Virtual network name",true);case SUBNET_CREATE->s.string("vnetName","Virtual network name",true).string("subnetName","Subnet name",true).string("addressPrefix","Address prefix",true);case NSG_CREATE->s.string("nsgName","Network security group name",true).string("location","Azure region",true);case AKS_GET,AKS_DELETE->s.string("clusterName","AKS cluster name",true);case AKS_CREATE->s.string("clusterName","AKS cluster name",true).string("location","Azure region",true).string("dnsPrefix","DNS prefix",true).integer("nodeCount","Node count",false).withDefault("nodeCount",1).string("vmSize","Node VM size",false).withDefault("vmSize","Standard_DS2_v2").string("kubernetesVersion","Kubernetes version",false);}
  if(op.destructive)s.bool("confirmed","Confirm destructive action",true).withDefault("confirmed",false);return s.build();}

 public NodeExecutionResult execute(NodeExecutionContext e){AzureOperation op=AzureOperation.from(e.nodeType());if(op==null)return NodeExecutionResult.failure("AZURE_UNKNOWN_OPERATION","Unknown Azure node type: "+e.nodeType());NodeConfiguration c=e.configuration();try{if(op.destructive&&!c.getBoolean("confirmed",false))return NodeExecutionResult.failure("AZURE_CONFIRMATION_REQUIRED","Set confirmed to true before running this destructive Azure operation.");String sub=c.requireString("subscriptionId"),rg=c.requireString("resourceGroup");AzureCredentials credentials=AzureCredentials.parse(context.secrets().require(c.requireString("credentialsSecret")));String token=auth.token(context.http(),credentials,e.timeoutMillis());Request request=request(op,c,sub,rg);HttpRequestSpec spec=HttpRequestSpec.builder(request.method,"https://management.azure.com"+request.path).header("Authorization","Bearer "+token).header("Content-Type","application/json").body(request.body).timeoutMillis(e.timeoutMillis()).build();HttpResponseView response=context.http().execute(spec);if(!response.isSuccess())return NodeExecutionResult.failure("AZURE_API_ERROR","Azure returned HTTP "+response.statusCode()+": "+safe(response.body()),response.statusCode()==429||response.statusCode()>=500);Map<String,Object> out=new LinkedHashMap<>();out.put("success",true);out.put("operation",op.name());out.put("subscriptionId",sub);out.put("resourceGroup",rg);out.put("statusCode",response.statusCode());out.put("response",response.body().isBlank()?Map.of():Json.parse(response.body()));String async=response.firstHeader("Azure-AsyncOperation");if(async==null)async=response.firstHeader("Location");out.put("asyncOperationUrl",async);return NodeExecutionResult.success(out);}catch(PluginConfigurationException ex){return NodeExecutionResult.failure("AZURE_MISCONFIGURED",ex.getMessage());}catch(AzureException ex){return NodeExecutionResult.failure(ex.code,ex.getMessage(),ex.retryable);}catch(RuntimeException ex){return NodeExecutionResult.failure("AZURE_EXECUTION_ERROR",safe(ex.getMessage()),true);}}

 private static Request request(AzureOperation op,NodeConfiguration c,String sub,String rg){String root="/subscriptions/"+enc(sub)+"/resourceGroups/"+enc(rg);String path,method="GET",body="";switch(op){case VM_LIST->path=root+"/providers/Microsoft.Compute/virtualMachines?api-version=2024-07-01";case VM_GET->path=root+"/providers/Microsoft.Compute/virtualMachines/"+enc(c.requireString("vmName"))+"?api-version=2024-07-01&$expand=instanceView";case VM_START,VM_DEALLOCATE,VM_RESTART->{method="POST";String action=op==AzureOperation.VM_START?"start":op==AzureOperation.VM_DEALLOCATE?"deallocate":"restart";path=root+"/providers/Microsoft.Compute/virtualMachines/"+enc(c.requireString("vmName"))+"/"+action+"?api-version=2024-07-01";}case VM_DELETE->{method="DELETE";path=root+"/providers/Microsoft.Compute/virtualMachines/"+enc(c.requireString("vmName"))+"?api-version=2024-07-01";}case VM_CREATE->{method="PUT";path=root+"/providers/Microsoft.Compute/virtualMachines/"+enc(c.requireString("vmName"))+"?api-version=2024-07-01";body=vmBody(c);}case VNET_LIST->path=root+"/providers/Microsoft.Network/virtualNetworks?api-version=2024-05-01";case VNET_DELETE->{method="DELETE";path=root+"/providers/Microsoft.Network/virtualNetworks/"+enc(c.requireString("vnetName"))+"?api-version=2024-05-01";}case VNET_CREATE->{method="PUT";path=root+"/providers/Microsoft.Network/virtualNetworks/"+enc(c.requireString("vnetName"))+"?api-version=2024-05-01";body=Json.write(Map.of("location",c.requireString("location"),"properties",Map.of("addressSpace",Map.of("addressPrefixes",List.of(c.requireString("addressPrefix"))))));}case SUBNET_CREATE->{method="PUT";path=root+"/providers/Microsoft.Network/virtualNetworks/"+enc(c.requireString("vnetName"))+"/subnets/"+enc(c.requireString("subnetName"))+"?api-version=2024-05-01";body=Json.write(Map.of("properties",Map.of("addressPrefix",c.requireString("addressPrefix"))));}case NSG_CREATE->{method="PUT";path=root+"/providers/Microsoft.Network/networkSecurityGroups/"+enc(c.requireString("nsgName"))+"?api-version=2024-05-01";body=Json.write(Map.of("location",c.requireString("location"),"properties",Map.of()));}case AKS_LIST->path=root+"/providers/Microsoft.ContainerService/managedClusters?api-version=2024-05-01";case AKS_GET->path=root+"/providers/Microsoft.ContainerService/managedClusters/"+enc(c.requireString("clusterName"))+"?api-version=2024-05-01";case AKS_DELETE->{method="DELETE";path=root+"/providers/Microsoft.ContainerService/managedClusters/"+enc(c.requireString("clusterName"))+"?api-version=2024-05-01";}case AKS_CREATE->{method="PUT";path=root+"/providers/Microsoft.ContainerService/managedClusters/"+enc(c.requireString("clusterName"))+"?api-version=2024-05-01";body=aksBody(c);}default->throw new IllegalArgumentException("Unsupported operation");}return new Request(method,path,body);}
 private static String vmBody(NodeConfiguration c){Map<String,Object> image=Map.of("publisher",c.getString("imagePublisher","Canonical"),"offer",c.getString("imageOffer","0001-com-ubuntu-server-jammy"),"sku",c.getString("imageSku","22_04-lts-gen2"),"version",c.getString("imageVersion","latest"));Map<String,Object> linux=Map.of("disablePasswordAuthentication",true,"ssh",Map.of("publicKeys",List.of(Map.of("path","/home/"+c.requireString("adminUsername")+"/.ssh/authorized_keys","keyData",c.requireString("sshPublicKey")))));Map<String,Object> props=new LinkedHashMap<>();props.put("hardwareProfile",Map.of("vmSize",c.getString("vmSize","Standard_B2s")));props.put("storageProfile",Map.of("imageReference",image,"osDisk",Map.of("createOption","FromImage")));props.put("osProfile",Map.of("computerName",c.requireString("vmName"),"adminUsername",c.requireString("adminUsername"),"linuxConfiguration",linux));props.put("networkProfile",Map.of("networkInterfaces",List.of(Map.of("id",c.requireString("networkInterfaceId")))));return Json.write(Map.of("location",c.requireString("location"),"properties",props));}
 private static String aksBody(NodeConfiguration c){Map<String,Object> props=new LinkedHashMap<>();props.put("dnsPrefix",c.requireString("dnsPrefix"));props.put("agentPoolProfiles",List.of(Map.of("name","systempool","count",c.getInt("nodeCount",1),"vmSize",c.getString("vmSize","Standard_DS2_v2"),"mode","System","osType","Linux","type","VirtualMachineScaleSets")));String version=c.getString("kubernetesVersion",null);if(version!=null&&!version.isBlank())props.put("kubernetesVersion",version);return Json.write(Map.of("location",c.requireString("location"),"identity",Map.of("type","SystemAssigned"),"properties",props));}
 private static String enc(String s){return AzureAuth.enc(s);}private static String safe(String s){if(s==null)return "Azure request failed";String x=s.replaceAll("[\\r\\n]+"," ");return x.length()>500?x.substring(0,500):x;}private record Request(String method,String path,String body){}
}
