package com.orchpilot.workflow.controller;

import com.orchpilot.workflow.scheduler.ScheduleConfig;
import com.orchpilot.workflow.scheduler.SchedulerExpressionBuilder;
import com.orchpilot.workflow.scheduler.WorkflowScheduleService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Turns a friendly schedule configuration into its cron, a plain-English description, and the next few run
 * times — so the designer can show a live preview without the browser ever building or parsing cron itself.
 *
 * <p>Stateless: it computes from the configuration in the request and touches no workflow, which is what lets
 * the preview update on every keystroke in the builder while a workflow is still a draft on screen. The cron
 * the scheduler eventually runs is generated by the same {@link SchedulerExpressionBuilder} when the workflow is
 * saved, so what the preview shows and what runs are guaranteed to agree.
 */
@RestController
@RequestMapping("/api/workflows/schedule")
@Tag(name = "Scheduler", description = "Friendly schedule preview and next-run calculation")
public class SchedulerController {

    private static final int MAX_RUNS = 20;

    private final SchedulerExpressionBuilder builder;
    private final WorkflowScheduleService scheduleService;

    public SchedulerController(SchedulerExpressionBuilder builder, WorkflowScheduleService scheduleService) {
        this.builder = builder;
        this.scheduleService = scheduleService;
    }

    /** A schedule to preview, with the timezone its times are read in and how many upcoming runs to compute. */
    public record PreviewRequest(ScheduleConfig schedule, String timezone, Integer count) {
    }

    /**
     * The preview.
     *
     * @param cron          the generated Spring cron (shown to advanced users, never required of others)
     * @param description   the plain-English sentence a normal user reads
     * @param timezone      the zone the runs are computed in
     * @param nextRuns      the upcoming run times, soonest first
     */
    public record PreviewResponse(String cron, String description, String timezone, List<Instant> nextRuns) {
    }

    @PreAuthorize("hasAuthority('WORKFLOW_VIEW')")
    @PostMapping("/preview")
    @Operation(summary = "Preview a schedule",
            description = "Builds the cron, a human-readable description, and the next few run times from the "
                    + "friendly configuration. A test run — it computes fire times without executing the "
                    + "workflow. Answers 400 with a readable message when the configuration is invalid.")
    public PreviewResponse preview(@RequestBody PreviewRequest request) {
        ScheduleConfig schedule = request.schedule();
        String timezone = request.timezone();
        // buildCron validates first, so an invalid configuration fails here with a readable message.
        String cron = builder.buildCron(schedule);
        String description = builder.describe(schedule, timezone);

        int count = request.count() == null ? 5 : Math.min(Math.max(1, request.count()), MAX_RUNS);
        List<Instant> runs = new ArrayList<>();
        Instant cursor = Instant.now();
        for (int i = 0; i < count; i++) {
            Instant next = scheduleService.nextFireAfter(cron, timezone, cursor);
            if (next == null) {
                break;
            }
            runs.add(next);
            cursor = next;
        }
        return new PreviewResponse(cron, description, timezone, runs);
    }

    /** A raw cron to reconstruct into friendly choices, so editing an existing schedule shows dropdowns. */
    public record ParseRequest(String cron, String timezone) {
    }

    @PreAuthorize("hasAuthority('WORKFLOW_VIEW')")
    @PostMapping("/parse")
    @Operation(summary = "Reconstruct a friendly configuration from an existing cron",
            description = "Best-effort: a cron this builder could have produced comes back as the matching "
                    + "frequency and choices; a hand-written one that fits no shape comes back as CUSTOM "
                    + "carrying the cron. Used when opening an existing schedule for editing.")
    public ParseResponse parse(@RequestBody ParseRequest request) {
        ScheduleConfig config = builder.fromCron(request.cron());
        return new ParseResponse(config, builder.describe(config, request.timezone()));
    }

    /** The reconstructed configuration and its description. */
    public record ParseResponse(ScheduleConfig schedule, String description) {
    }
}
